# Generated by Django 3.2.8 on 2021-10-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211029_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='property',
            new_name='propertys',
        ),
        migrations.AlterField(
            model_name='our_service',
            name='is_active',
            field=models.BooleanField(choices=[('true', 'TRUE'), ('false', 'FALSE')], default='true', max_length=6),
        ),
    ]
