# Generated by Django 3.2.8 on 2021-10-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211029_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_service',
            name='is_active',
            field=models.BooleanField(choices=[('true', 'TRUE'), ('false', 'FALSE')], default='TRUE', max_length=6),
        ),
    ]
