# Generated by Django 3.2.8 on 2021-10-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_our_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_service',
            name='is_active',
            field=models.BooleanField(choices=[('active', 'TRUE'), ('not active', 'FALSE')], default='TRUE', max_length=11),
        ),
    ]
