# Generated by Django 3.2.8 on 2021-10-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_our_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_service',
            name='is_active',
            field=models.BooleanField(choices=[('active', 'ACTIVE'), ('not_active', 'NOT_ACTIVE')], default='active', max_length=11),
        ),
    ]
