# Generated by Django 3.2.8 on 2021-10-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211029_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_partner',
            name='image',
            field=models.ImageField(upload_to='partner_logo/'),
        ),
        migrations.AlterField(
            model_name='our_project',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='propertys',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='public_review',
            name='icon',
            field=models.ImageField(upload_to='profile_pic/'),
        ),
    ]
