# Generated by Django 3.2.8 on 2021-10-29 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211029_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public_review',
            name='icon',
        ),
        migrations.AddField(
            model_name='public_review',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='review_profile_pic/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='our_project',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
    ]
