# Generated by Django 3.2.8 on 2021-10-30 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20211030_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_project',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='our_project',
            name='architects',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_project',
            name='area',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_project',
            name='category',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_project',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_project',
            name='image2',
            field=models.ImageField(default=1, upload_to='project_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_project',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_project',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_project',
            name='manufactures',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_project',
            name='project_year',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
