# Generated by Django 3.2.8 on 2021-10-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_our_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_project',
            old_name='project_name',
            new_name='title',
        ),
    ]
