# Generated by Django 3.2.8 on 2021-10-31 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_top_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_image',
            old_name='construction_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='top_image',
            name='manpower_image',
        ),
        migrations.RemoveField(
            model_name='top_image',
            name='realestate_image',
        ),
        migrations.RemoveField(
            model_name='top_image',
            name='security_image',
        ),
        migrations.AddField(
            model_name='top_image',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top_image',
            name='service_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=99),
            preserve_default=False,
        ),
    ]
