# Generated by Django 3.2.8 on 2021-10-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20211031_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='our_address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='our_address',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='our_address',
            name='is_active',
            field=models.CharField(choices=[('true', 'TRUE'), ('false', 'FALSE')], default='false', max_length=6),
        ),
    ]
