# Generated by Django 3.2.8 on 2021-10-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20211031_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_project',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
