# Generated by Django 3.2.8 on 2021-10-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_our_project_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='our_project',
            unique_together={('slug', 'title')},
        ),
    ]
