# Generated by Django 3.2.8 on 2021-10-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_our_project_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='our_project',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='our_project',
            name='slug',
        ),
    ]
